"""baseline: nomenklatura tables

Revision ID: d92ef7324161
Revises:
Create Date: 2026-10-01 12:04:06.702373

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d92ef7324161"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ("nomenklatura",)
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cache",
        sa.Column("key", sa.Unicode(), nullable=False),
        sa.Column("text", sa.Unicode(), nullable=True),
        sa.Column("dataset", sa.Unicode(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_index(op.f("ix_cache_timestamp"), "cache", ["timestamp"], unique=False)
    op.create_table(
        "resolver",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("target", sa.Unicode(length=512), nullable=True),
        sa.Column("source", sa.Unicode(length=512), nullable=True),
        sa.Column("judgement", sa.Unicode(length=14), nullable=False),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("user", sa.Unicode(length=512), nullable=False),
        sa.Column("created_at", sa.Unicode(length=28), nullable=True),
        sa.Column("deleted_at", sa.Unicode(length=28), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_resolver_created_at"), "resolver", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_resolver_deleted_at"), "resolver", ["deleted_at"], unique=False
    )
    op.create_index(op.f("ix_resolver_source"), "resolver", ["source"], unique=False)
    op.create_index(op.f("ix_resolver_target"), "resolver", ["target"], unique=False)
    op.create_index(
        "resolver_judgement_score",
        "resolver",
        ["judgement", "score"],
        unique=False,
    )
    op.create_index(
        "resolver_source_target_uniq",
        "resolver",
        ["source", "target"],
        unique=True,
        sqlite_where=sa.text("deleted_at IS NULL"),
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "statement",
        sa.Column("id", sa.Unicode(length=255), nullable=False),
        sa.Column("entity_id", sa.Unicode(length=255), nullable=False),
        sa.Column("canonical_id", sa.Unicode(length=255), nullable=False),
        sa.Column("prop", sa.Unicode(length=255), nullable=False),
        sa.Column("prop_type", sa.Unicode(length=255), nullable=False),
        sa.Column("schema", sa.Unicode(length=255), nullable=False),
        sa.Column("value", sa.Unicode(length=65535), nullable=False),
        sa.Column("original_value", sa.Unicode(length=65535), nullable=True),
        sa.Column("dataset", sa.Unicode(length=255), nullable=True),
        sa.Column("origin", sa.Unicode(length=255), nullable=True),
        sa.Column("lang", sa.Unicode(length=255), nullable=True),
        sa.Column("external", sa.Boolean(), nullable=False),
        sa.Column("first_seen", sa.DateTime(), nullable=True),
        sa.Column("last_seen", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_statement_canonical_id"), "statement", ["canonical_id"], unique=False
    )
    op.create_index(
        op.f("ix_statement_dataset"), "statement", ["dataset"], unique=False
    )
    op.create_index(
        op.f("ix_statement_entity_id"), "statement", ["entity_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_statement_entity_id"), table_name="statement")
    op.drop_index(op.f("ix_statement_dataset"), table_name="statement")
    op.drop_index(op.f("ix_statement_canonical_id"), table_name="statement")
    op.drop_table("statement")
    op.drop_index(
        "resolver_source_target_uniq",
        table_name="resolver",
        sqlite_where=sa.text("deleted_at IS NULL"),
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index("resolver_judgement_score", table_name="resolver")
    op.drop_index(op.f("ix_resolver_target"), table_name="resolver")
    op.drop_index(op.f("ix_resolver_source"), table_name="resolver")
    op.drop_index(op.f("ix_resolver_deleted_at"), table_name="resolver")
    op.drop_index(op.f("ix_resolver_created_at"), table_name="resolver")
    op.drop_table("resolver")
    op.drop_index(op.f("ix_cache_timestamp"), table_name="cache")
    op.drop_table("cache")
    # ### end Alembic commands ###
